version: 2
jobs:
  build: 
    working_directory: ~/warn_test # directory where steps will run
    docker:
      - image: circleci/node:9.9.0
    steps:
      - checkout # step to check out source code to working directory
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - run: npm run build
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths: build/*